### ISSUE TITLE
Hookshot r9  - Constant Motion When Still Connected

### ISSUE THREAD

**Issue by rxay579** [CammiePone/Hookshot#8] opened 2020-08-06 22:47 UTC
I don't know if this is working as intended, but if you don't release the hookshot before you reach the endpoint, then while you're at the endpoint, it pulls the player around pretty erratically and sometimes quite quickly.
It seems that when the player gets there, the hookshot relaxes for a moment, then quickly reels back towards the endpoint.
If you release while the hookshot you are in motion at the endpoint, it can throw you far enough to be dangerous instead of just dropping you.  Dropping would also be dangerous, but more predictable.

Was expecting(hoping) the player position to be stable enough at the end of the connection so that the hookshot could be used for building/placing blocks in hard to reach places.
Perhaps the reeling speed could be reduced or removed once the player reaches the endpoint?

**Comment by CammiePone** [comment] 2020-08-06 22:51
Ight so, this is _technically_ working as intended, but I've heard people wanting it fixed, and I've just yet to fix it. It shouldn't be _that_ hard to fix, I just haven't gotten around to it.

Thank you for this report tho, as it should hopefully serve as a reminder for it!

**Comment by FewerFlaws** [comment] 2020-12-17 08:11
I would also like to see this change.  These hookshots don't have weird rope physics like those in Campanion because they shoot straight, but this erratic behavior at the end of the retraction severely compromises the feel.

Ideally it would pull you to the location and then stick you in place until you either jump (which would move you up like a normal jump) or right click to disconnected the hook, allowing you to fall.

**Comment by CammiePone** [comment] 2021-05-31 01:58
This has been fixed now in dev, once CurseForge is back up and the last few cosmetic changes occur, I will push out an update @FewerFlaws @rxay579

**Closed by CammiePone** 2021-05-31 01:58 UTC
Labels: bug
